# generated by TestGen/TestCompress.hs

import goldilocks_hash/types

const refInp1* : array[4, F] = 
  [ toF( 0x0000000000000001'u64 )
  , toF( 0x0000000000000002'u64 )
  , toF( 0x0000000000000003'u64 )
  , toF( 0x0000000000000004'u64 )
  ]


const refInp2* : array[4, F] = 
  [ toF( 0x0000000000000005'u64 )
  , toF( 0x0000000000000006'u64 )
  , toF( 0x0000000000000007'u64 )
  , toF( 0x0000000000000008'u64 )
  ]


const refOutKey0* : array[4, F] = 
  [ toF( 0xc4a4082f411ba790'u64 )
  , toF( 0x98c2ed7546c44cce'u64 )
  , toF( 0xc9404f373b78c979'u64 )
  , toF( 0x65d6b3c998920f59'u64 )
  ]


const refOutKey1* : array[4, F] = 
  [ toF( 0xca47449a05283778'u64 )
  , toF( 0x08d3ced2020391ac'u64 )
  , toF( 0xda461ea45670fb12'u64 )
  , toF( 0x57f2c0b6c98a05c5'u64 )
  ]


const refOutKey2* : array[4, F] = 
  [ toF( 0xe6fcec96a7a7f4b0'u64 )
  , toF( 0x3002a22356daa551'u64 )
  , toF( 0x899e2c1075a45f3f'u64 )
  , toF( 0xf07e38ccb3ade312'u64 )
  ]


const refOutKey3* : array[4, F] = 
  [ toF( 0x9930cff752b046fb'u64 )
  , toF( 0x41570687cadcea0b'u64 )
  , toF( 0x3ac093a5a92066c7'u64 )
  , toF( 0xc45c75a3911cde87'u64 )
  ]



