# generated by TestGen/TestCompress.hs

import goldilocks_hash/types

const refInp1* : array[4, F] = 
  [ toF( 0x0000000000000001'u64 )
  , toF( 0x0000000000000002'u64 )
  , toF( 0x0000000000000003'u64 )
  , toF( 0x0000000000000004'u64 )
  ]


const refInp2* : array[4, F] = 
  [ toF( 0x0000000000000005'u64 )
  , toF( 0x0000000000000006'u64 )
  , toF( 0x0000000000000007'u64 )
  , toF( 0x0000000000000008'u64 )
  ]


const refOutKey0* : array[4, F] = 
  [ toF( 0x794c4b4308cb8286'u64 )
  , toF( 0xe6ca7b9c49970427'u64 )
  , toF( 0x89b2e0614bc0af93'u64 )
  , toF( 0xd0f63984b0d43850'u64 )
  ]


const refOutKey1* : array[4, F] = 
  [ toF( 0xe29e85f8f1782476'u64 )
  , toF( 0xd32a5179356e274f'u64 )
  , toF( 0x00fd4b778d2a019e'u64 )
  , toF( 0x060ca2a006f4815a'u64 )
  ]


const refOutKey2* : array[4, F] = 
  [ toF( 0xd3b556e546fe9ea5'u64 )
  , toF( 0x5d99e5d70188e012'u64 )
  , toF( 0x6bd1f2c0940918f4'u64 )
  , toF( 0xe25b659a26b33f27'u64 )
  ]


const refOutKey3* : array[4, F] = 
  [ toF( 0x12b810db565f56db'u64 )
  , toF( 0x25f66032a99e4e52'u64 )
  , toF( 0x3ceca3fb262075b4'u64 )
  , toF( 0x77602ef03231a802'u64 )
  ]



